blank_issues_enabled: false
contact_links:
    - name: â”å¸®åŠ©
      url: https://github.com/WhatDamon/Simplay-Player/discussions/categories/q-a
      about: è½¯ä»¶æ²¡æœ‰æŒ‰ç…§é¢„æœŸå·¥ä½œ? æˆ–è€…å°±æ˜¯ä¸€äº›ç®—ä¸ä¸Š BUG çš„å°é—®é¢˜? å‘å¸ƒä¸€æ¡é—®ç­”è®¨è®º!
    - name: ğŸ˜ŠåŠŸèƒ½è¯·æ±‚
      url: https://github.com/WhatDamon/Simplay-Player/discussions/categories/%E6%83%B3%E6%B3%95
      about: æœ‰ä»€ä¹ˆæ–°å¥‡çš„æƒ³æ³•å—? æ¥è¿™é‡Œæå‡º, è®©æˆ‘ä»¬ä¸€èµ·è®¨è®º!
